### PR TITLE
pam/pam-exec: Use an enum for the action types

### PR DESCRIPTION
**Pull request by 3v1n0**
Using strings can be dangerous in case something changes, plus we are doing string comparisons for some actions that can be handle better with a switch.

Just few cleanups I noticed...

### CODE REVIEW

**Review by didrocks — CHANGES_REQUESTED** [review]
QA tests are not passing (I didn’t look at the details). Otherwise the changes looks good to me! approving once the tests pass.

**Comment by 3v1n0** [comment]
Ah, ok... it was a pedant check on sanitizer, but fair enough. It should be fixed now.

**Review by denisonbarbosa — APPROVED** [review]

**Comment by 3v1n0** [comment]
Anything else to do here?

**Comment by denisonbarbosa** [comment]
> Anything else to do here?

@didrocks (waiting for your approval)

**Review by didrocks — APPROVED** [review]

**Review by denisonbarbosa — APPROVED** [review]

**Pull request merged**
