### PR TITLE
testutils/coverage: Create coverage directory if provided

### PR DESCRIPTION
**Pull request by 3v1n0**
This also implies cleaning up it first if already existent because otherwise we may get broken reports when repeating the tests with a coverage dir set.

Basically I got tired of having to manually remove, and create a clean dir every time I wanted to run the tests, as not doing this implies that the coverage report is broken and not respecting the provided arguments.

### CODE REVIEW

**Comment by didrocks** [comment]
This breaks the "serving locally and refreshing the page" by having a local http server continously running inside the directory. Please ensure we can still work with this.

**Comment by 3v1n0** [comment]
> This breaks the "serving locally and refreshing the page" by having a local http server continously running inside the directory. Please ensure we can still work with this.

Not sure how that would work :)

How do I check that?

**Comment by didrocks** [comment]
Most of the team members are running a local webserver serving the http pages generated into that directory. This is continously executed and use that directory as a serving files there, including index.html. If you remove the directory, then it will serve its previous directory.

**Comment by 3v1n0** [comment]
> Most of the team members are running a local webserver serving the http pages generated into that directory. This is continously executed and use that directory as a serving files there, including index.html. If you remove the directory, then it will serve its previous directory.

Mhmh, so I'll just remove the content of it I assume... Thing is that if you re-run the tests with using that dir it would still give you bad results, so you've to drop the contents.

**Comment by didrocks** [comment]
Are you sure you found the root cause? Because it’s supposed to overwrite the current content and it works in all our other projects…

**Comment by 3v1n0** [comment]
Nope... But when I re-run the tests the generated index file is just wrong... The coverage values (percentages) are maybe correct, but the file shows green/dark areas are no sense.

Anyways, at least just creating the dir if not exists would be a first improvement :smile:

**Comment by didrocks** [comment]
I don’t like that we diverge between the projects without understanding the real need, so I suggest that we either identify the root cause or let it the same than the other projects until we factor it out.

**Comment by 3v1n0** [comment]
Ok, I see... It's quite hard to reproduce, but indeed I got it often when not cleaning things.

However... I can definitely look better when that occurs.

Meanwhile, I still think it would be convenient to create the directory when the parameter is provided instead of having to do it manually everywhere, and if that's needed I can do replicate this in other projects too.

**Pull request closed without merging**
