### PR TITLE
Fix example broker D-Bus XML file

### PR DESCRIPTION
**Pull request by adombeck**
"a{s}s" is not a valid GVariant type, it should be "a{ss}" instead.

### CODE REVIEW

**Review by 3v1n0 — APPROVED** [review]
Oh... Indeed!

**Comment by michaelwildvarian** [comment]
Only thing that worries me a bit is that it also shows up in the Entra ID broker: https://github.com/ubuntu/authd-oidc-brokers/blob/2c443ba1791f326e70e0d5d042ca7aa5d13017ce/internal/dbusservice/dbusservice.go#L29.

**Comment by 3v1n0** [comment]
I've the feeling that dbus variant parsing isn't doing things properly?

But we're definitely wrong there too, in fact:

```
$ gdbus introspect --system --dest com.ubuntu.authd.MSEntraID --object-path /com/ubuntu/authd/MSEntraID 
node /com/ubuntu/authd/MSEntraID {
  interface com.ubuntu.authd.Broker {
    methods:
      NewSession(in  s username,
                 in  s lang,
                 in  s mode,
                 out s sessionID,
                 out s encryptionKey);
      GetAuthenticationModes(in  s sessionID,
                             in  a{s}s supportedUILayouts,
                             out a{s}s authenticationModes);
      SelectAuthenticationMode(in  s sessionID,
                               in  s authenticationModeName,
                               out a{s}s uiLayoutInfo);
      IsAuthenticated(in  s sessionID,
                      in  s authenticationData,
                      out s access,
                      out s data);
      EndSession(in  s sessionID);
      CancelIsAuthenticated(in  s sessionID);
      UserPreCheck(in  s username);
    signals:
    properties:
  };
  interface org.freedesktop.DBus.Introspectable {
    methods:
      Introspect(out s out);
    signals:
    properties:
  };
};
```

Now, this doesn't seem to happen in the example broker we've in tests:

```
$ gdbus introspect --system --dest com.ubuntu.authd.ExampleBroker --object-path /com/ubuntu/authd/ExampleBroker 
node /com/ubuntu/authd/ExampleBroker {
  interface org.freedesktop.DBus.Introspectable {
    methods:
      Introspect(out s out);
    signals:
    properties:
  };
  interface com.ubuntu.authd.Broker {
    methods:
      CancelIsAuthenticated(in  s arg_0);
      EndSession(in  s arg_0);
      GetAuthenticationModes(in  s arg_0,
                             in  aa{ss} arg_1,
                             out aa{ss} arg_2);
      IsAuthenticated(in  s arg_0,
                      in  s arg_1,
                      out s arg_2,
                      out s arg_3);
      NewSession(in  s arg_0,
                 in  s arg_1,
                 in  s arg_2,
                 out s arg_3,
                 out s arg_4);
      SelectAuthenticationMode(in  s arg_0,
                               in  s arg_1,
                               out a{ss} arg_2);
      UserPreCheck(in  s arg_0,
                   out s arg_1);
    signals:
    properties:
  };
};
```

And they both work fine with the same server, so I've the feeling that in some way the go dbus implementation handles this in the same way... mhmh

**Comment by 3v1n0** [comment]
@adombeck FYI the racy failure that you got in the `(coverage)` job is fixed by #616 (I was imagining it to happen again! :))

e.g. https://github.com/ubuntu/authd/actions/runs/11708304677/job/32609750206?pr=619

**Comment by michaelwildvarian** [comment]
The .NET implementation of https://github.com/tmds/Tmds.DBus at least fails with `a{s}s`.

**Comment by adombeck** [comment]
> Only thing that worries me a bit is that it also shows up in the Entra ID broker: https://github.com/ubuntu/authd-oidc-brokers/blob/2c443ba1791f326e70e0d5d042ca7aa5d13017ce/internal/dbusservice/dbusservice.go#L29.

I opened https://github.com/ubuntu/authd-oidc-brokers/pull/193 to fix that as well

**Comment by michaelwildvarian** [comment]
Thanks for the prompt resolution on both issues!

**Pull request merged**
