### PR TITLE
Don't try to get passwd entry for UIDs which we know are orphaned

### LINKED ISSUE #542: Issue: Starting authd times out if there are (many) processes of an orphaned UID
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

I'm experiencing this issue in my test VM. The orphaned UID is from a user that was created by authd before but has been deleted from the database. I'm not sure what caused it to be deleted.

### Steps to reproduce

I did not try to reproduce the issue, but I suspect that those steps led to it:

1. Log in via device authentication in GDM
2. Select "Switch user" in the GNOME system menu
3. Log in with another (local) user
4. Restart authd

#### authd version
```
authd	Dev
```

#### authd-msentraid broker version
```
name:      authd-msentraid
summary:   MSEntra ID broker for authd
publisher: Canonical**
store-url: https://snapcraft.io/authd-msentraid
license:   GPL-3.0
description: |
  This is the MS Entra ID broker snap for authd  to provide MS Entra ID OIDC
  based authentication on Ubuntu with authd.
services:
  authd-msentraid: simple, enabled, active
snap-id:      vS3oJLMss6lgWwoFcPqYDUA2HB20I1Dc
tracking:     0.x/edge
refresh-date: today at 13:46 CEST
channels:
  0.x/stable:    0.1 2024-09-16 (44) 17MB -
  0.x/candidate: ^                        
  0.x/beta:      ^                        
  0.x/edge:      0.1 2024-09-17 (49) 18MB -
installed:       0.1            (49) 18MB -
```

#### gnome-shell version
```
gnome-shell:
  Installed: 46.3.1-1ubuntu1~24.04.1authd1
  Candidate: 46.3.1-1ubuntu1~24.04.1authd1
  Version table:
 *** 46.3.1-1ubuntu1~24.04.1authd1 500
        500 https://ppa.launchpadcontent.net/ubuntu-enterprise-desktop/authd-edge/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
     46.3.1-1ubuntu1~24.04.1 500
        500 https://ppa.launchpadcontent.net/ubuntu-enterprise-desktop/authd/ubuntu noble/main amd64 Packages
     46.0-0ubuntu6~24.04.4 500
        500 http://de.archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages
     46.0-0ubuntu6~24.04.3 500
        500 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages
     46.0-0ubuntu5 500
        500 http://de.archive.ubuntu.com/ubuntu noble/main amd64 Packages
```

#### Distribution
```
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

#### Logs
```
[104133.320352] ubuntu systemd[1]: Starting authd.service - Authd daemon service...
[104133.347898] ubuntu authd[68820]: INFO No configuration file: Config File "authd" Not Found in "[/ /etc/authd /usr/libexec]".
[104133.347898] ubuntu authd[68820]: We will only use the defaults, env variables or flags.
[104133.348430] ubuntu authd[68820]: DEBUG Debug mode is enabled
[104133.348430] ubuntu authd[68820]: DEBUG Building authd object
[104133.348430] ubuntu authd[68820]: DEBUG Building broker detection
[104133.349143] ubuntu authd[68820]: DEBUG Auto-detecting brokers
[104133.349189] ubuntu authd[68820]: DEBUG Loading broker from "/etc/authd/brokers.d/authd-msentraid.conf"
[104133.349189] ubuntu authd[68820]: DEBUG Dbus broker configuration at "/etc/authd/brokers.d/authd-msentraid.conf"
[104138.377286] ubuntu authd[68820]: 2024/09/18 17:02:01 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104143.380557] ubuntu authd[68820]: 2024/09/18 17:02:06 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104148.383598] ubuntu authd[68820]: 2024/09/18 17:02:11 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104153.386581] ubuntu authd[68820]: 2024/09/18 17:02:16 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104158.389934] ubuntu authd[68820]: 2024/09/18 17:02:21 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104163.393381] ubuntu authd[68820]: 2024/09/18 17:02:26 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104168.396535] ubuntu authd[68820]: 2024/09/18 17:02:31 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104173.398968] ubuntu authd[68820]: 2024/09/18 17:02:36 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104178.402062] ubuntu authd[68820]: 2024/09/18 17:02:41 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104183.405040] ubuntu authd[68820]: 2024/09/18 17:02:46 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104188.407772] ubuntu authd[68820]: 2024/09/18 17:02:51 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104193.409878] ubuntu authd[68820]: 2024/09/18 17:02:56 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104198.413336] ubuntu authd[68820]: 2024/09/18 17:03:01 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104203.416543] ubuntu authd[68820]: 2024/09/18 17:03:06 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104208.419176] ubuntu authd[68820]: 2024/09/18 17:03:11 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104213.421684] ubuntu authd[68820]: 2024/09/18 17:03:16 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104218.423901] ubuntu authd[68820]: 2024/09/18 17:03:21 WARN Could not map active user ID to an actual user: user: unknown userid 296886116
[104223.414168] ubuntu systemd[1]: authd.service: start operation timed out. Terminating.
```

#### /etc/authd/brokers.d/authd-msentraid.conf
```
[authd]
name = Microsoft Entra ID
brand_icon = /snap/authd-msentraid/current/broker_icon.png
dbus_name = com.ubuntu.authd.MSEntraID
dbus_object = /com/ubuntu/authd/MSEntraID

```

#### authd-msentraid configuration
```
[oidc]
issuer = https://login.microsoftonline.com/<UUID redacted>/v2.0
client_id = <UUID redacted> 
#client_id = <UUID redacted>
```

### Double check your logs

- [X] I have redacted any sensitive information from the logs

### PR DESCRIPTION
**Pull request by adombeck**
I've encountered a case where each `getpwuid` call took 5 seconds, and because there were a lot of active processes from an orphaned user, we issued so many `getpwuid` calls that the start operation of the authd.service timed out. 

Closes #542
UDENG-4628

### CODE REVIEW

**Comment by adombeck** [comment]
Only the flaky test failed

**Comment by adombeck** [comment]
I wonder why we look up the username at all in https://github.com/ubuntu/authd/blob/30b89512acfc0f36729d3865deea94a217e6a204/internal/users/manager.go#L415-L415

Why don't we return the UIDs of the active users instead and use those to identify the users which we clean in https://github.com/ubuntu/authd/blob/30b89512acfc0f36729d3865deea94a217e6a204/internal/users/cache/db.go#L179-L181

@denisonbarbosa I see you wrote that code, do you remember the reason to use the username instead of the UID?

**Comment by denisonbarbosa** [comment]
> @denisonbarbosa I see you wrote that code, do you remember the reason to use the username instead of the UID?

IIRC, this is exactly to handle orphaned processes cases (you can see that we don't consider that user as being active). If we are dealing with one of those cases, we can safely remove the user entry in the database without risk of damaging a user session. Regarding the username, if you take a look at the rest of the code that depends on this (such as [cleaning the user from the local groups](https://github.com/ubuntu/authd/blob/f9f851540e6377fca18a45ce7a02d024c1dbd6e9/internal/users/localgroups/localgroups.go#L138)), you'll see that we need the username to pass as the argument for gpasswd. So, since we already did a NSS call to check for the user existence and, therefore, already have access to its username because of it, it's better to store this information and avoiding duplicating calls down the line.

**Comment by adombeck** [comment]
I pushed another commit which changes the code to not resolve the username via `user.LookupId`. I hope the commit message is explanation enough, but let me know if it's not.

**Review by denisonbarbosa — APPROVED** [review]
This looks good to me. Well done spotting the issue!

**Pull request merged**
