### PR TITLE
Copy improvements to golden files from broker repo

### PR DESCRIPTION
**Pull request by adombeck**
Copy the changes to the code for handling golden files from the broker repo.

UDENG-5447

### CODE REVIEW

**Comment by 3v1n0** [comment]
Wouldn't be better to have this somewhat public (or in a shared repo) so that we can import in both places?

**Comment by adombeck** [comment]
The PAM SSH integration test [failed](https://github.com/ubuntu/authd/actions/runs/12140827087/job/33851478431?pr=645) but I don't see any error in the output. @3v1n0 do you have an idea what's going on there?

**Comment by adombeck** [comment]
> The PAM SSH integration test [failed](https://github.com/ubuntu/authd/actions/runs/12140827087/job/33851478431?pr=645)

I can't reproduce that failure locally

**Comment by adombeck** [comment]
The failing tests are just flakiness, it's filed in https://github.com/ubuntu/authd/issues/673.

**Review by denisonbarbosa — CHANGES_REQUESTED** [review]
Changes look good besides one detail: you added the `golden` package directly under `internal/` instead of under `internal/testutils` as we talked about in the broker repo.

**Comment by adombeck** [comment]
>  Changes look good besides one detail: you added the golden package directly under internal/ instead of under internal/testutils as we talked about in the broker repo.

I moved it to `internal/testutils/golden/`.

**Review by denisonbarbosa — APPROVED** [review]
LGTM!

**Pull request merged**
