### PR TITLE
CONTRIBUTING.md: remove repeated line under getting started

### PR DESCRIPTION
**Pull request by shiv-tyagi**
Hi! I found this repeated line while going through the contributing guide. This PR removes the same.

I am new here. I found this project really interesting. Looking forward to making meaningful contributions to the project.

### CODE REVIEW

**Comment by shiv-tyagi** [comment]
Couldn't figure out what to fill in here while signing the Canonical CLA. Can anyone please help me with this?

image

**Comment by 3v1n0** [comment]
Oh, you can likely mention @didrocks there

**Comment by shiv-tyagi** [comment]
Thanks @3v1n0. I've signed the CLA. Can you please review this or redirect it to the right person?

Thanks in advance!

**Review by edibotopic — APPROVED** [review]
thanks for your contribution @shiv-tyagi -- well spotted!

**Pull request merged**
