### PR TITLE
issue-template: Add command to get shell and gdm logs

### PR DESCRIPTION
**Pull request by 3v1n0**

### CODE REVIEW

**Comment by adombeck** [comment]
The command I added in https://github.com/ubuntu/authd/pull/485 includes gdm logs. What is logged by gnome-shell that's relevant for us?

**Comment by 3v1n0** [comment]
Well, we can tail the last lines (e.g. `-n 200`) or just use `journalctl` to limit by time.

**Review by jibel — APPROVED** [review]
Thanks, this must also be added to Adrian's PR #485 .

**Comment by 3v1n0** [comment]
Let me know if you prefer to merge this first or close it instead so that can be handled all at once by @adombeck in #485

**Comment by jibel** [comment]
Not a problem so far, closing for now.

**Pull request closed without merging**
